version: "3"
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
      - "9999:9999"
    restart: always
    networks:
      - mynet
  chronograf:
    image: chronograf:1.5
    volumes:
      - chronograf_data:/var/lib/chronograf
    ports:
      - 127.0.0.1:8087:8888
    restart: always
    networks:
      - mynet
  grafana:
    image: grafana/grafana
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - mynet
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - mynet
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet
  prod:
    image: controllerbase/alpha-api
    networks:
      - mynet
    ports:
    - 8080:8080
  cons:
    image: controllerbase/alpha-cons
    networks:
      - mynet
volumes:
  influxdb_data:
  chronograf_data:
  grafana_data:
networks:
  mynet:
