name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Server.dockerfile --tag controllerbase/alpha-api
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - name: docker push controllerbase/alpha-api
      run: docker push controllerbase/alpha-api
    - name: docker push controllerbase/alpha-con
      run: docker push controllerbase/alpha-con
