name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Server.dockerfile --tag controllerbase/alpha-api:$(date +%s)

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Consumer.dockerfile --tag controllerbase/alpha-con:$(date +%s)
